title: 'Polaroider'
subtitle: 'Documentation'
codeurl: 'https://github.com/WickedFlame/Polaroider'
baseurl: '/Polaroider'
highlighter: rouge
exclude: [README.md']
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]